version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: python3 manage.py runserver 0:8000
    volumes:
      - ../django_tutorial:/app
    ports:
      - '8000:8000'